### ISSUE TITLE
Publish the vocabular in the same namespace

### ISSUE THREAD

**Issue by l00mi** [lindas-uc/bafu_ubd#3]
- Attach the Metadata from the udb28 spreadsheet (http://www.ubst.bafu.admin.ch/opendata/UBD0028.ods)
- Switch from example NS to http://environment.data.admin.ch/ubd/28/vocab/ NS

The idea is to show that also the column description is in the data model. (multilingual if possible)

**Comment by retog** [comment]
It has probably to little to do with e-government to be part of gont.ch, not sure.

**Comment by l00mi** [comment]
For now it is just important to have a Vocab to show the concept. The discussion which is the correct one will follow.

**Comment by ktk** [comment]
Wontfix
